### PR TITLE
Improved landing page UI

### PR DESCRIPTION
**Pull request by janakamarasena**
**Changes:**

1. Changed the font colour of "check out the features" to match the button colour of "Get started" 
- This gives the two a more connected feel whilst also giving a primary and secondary option feel.

2. Changed "Here's why you'll love it:" to "Here's why you'll love it" and increased font size.
- This makes it look like a sub-heading as everything under it follows it.

3. Removed coloured strip background and separator in the features.
- This gives a more connected flow to the features.
- The coloured stripes also distracts the viewers' eye from the features content.

4. Changed feature-section font to "Open Sans"
- Has a better look.
- Also licenced under [Apache License, Version 2.0](https://fonts.google.com/specimen/Open+Sans)

5. Increased the font-weight for the feature headings.
- This gives the feature headings a more instant focus to the viewers' eye.

### CODE REVIEW

**Comment by vaidap** [comment]
1, 2, 4 & 5 are super great -- big fan of Open Sans. 😄 
As for 3, removing the separators is definitely a good call, but the alternating blue/white allows the reader to easily see the separations; removing it completely makes it harder to read. Maybe we could get the best of both worlds by adding more padding to the sections/ having an even lighter blue background color?

**Comment by janakamarasena** [comment]
@vaidap lets add more padding and see before putting back the coloured stripes :) I'll update the PR soon :)

**Comment by janakamarasena** [comment]
@vaidap increased the padding and also increased the feature headings size to make the separation more visible. please check :)

**Comment by vaidap** [comment]
awesome work, i think it looks 💯 now. :D

**Comment by janakamarasena** [comment]
Thank you :)

**Comment by timabbott** [comment]
Merged as 10a1f786938a9cd1654e67757f8bebae32aad451, thanks @janakamarasena!

Sorry for the very slow merge!

**Comment by janakamarasena** [comment]
No worries :)

**Pull request closed without merging**
