### PR TITLE
Optimized images

### PR DESCRIPTION
**Pull request by akashnimare**
Issue - Page performance
Page affected - https://www.zulip.org
We were using some heavy png images which were making the page slow. I have tried to optimize(total reduced size ~1100kb) all those images so that performance and load time can be improved.

### CODE REVIEW

**Comment by lfaraone** [comment]
Hi @akashnimare — I merged this in. Out of curiosity, what did you use to optimise these images?

**Comment by akashnimare** [comment]
Hey @lfranchi 
Tools I have used -
1. https://tinypng.com/
2. https://compressor.io/
Tinypng is pretty good. Btw there is no change in resolution only the size gets reduced. It's a lossless compression.

**Comment by lfranchi** [comment]
I think you meant @lfaraone  :)

**Comment by akashnimare** [comment]
@lfranchi haha, my bad. I was sleepy at that time :)

**Comment by lfaraone** [comment]
@akashnimare thanks for the details, I'll check those out in the future.

**Pull request closed without merging**
