### PR TITLE
add analytics in features

### PR DESCRIPTION
**Pull request by blaze225**
Added entry for analytics in features.html

### CODE REVIEW

**Comment by timabbott** [comment]
@blaze225 I think we could probably make it sound a little more interesting than "various statistics" :).

@rishig thoughts on what a good description is?

**Comment by rishig** [comment]
"Up and to the right!"
"See granular summaries of your and your organization's activity."

**Comment by blaze225** [comment]
@rishig i should move analytics to the top right? right?

**Comment by rishig** [comment]
Probably towards the bottom of the page is fine; there are other more important things at the top :).

**Comment by timabbott** [comment]
Merged, thanks @blaze225!  I also added i18n here.  

We should do the same update to templates/zerver/features.html in zulip/zulip; can you port these changes over @blaze225?

**Comment by blaze225** [comment]
@timabbott sure, will do that.

**Pull request closed without merging**
