### PR TITLE
Added Footer and Updated Readme.md

### LINKED ISSUE #4: Footer needs to be added
@timabbott Do you think a good footer needs to be added here. Also docs on zulip.org and zulip.com/hello is slightly different. I am not sure it's intentional or not updated.

### PR DESCRIPTION
**Pull request by jajodiaraghav**
-Fixes #4 Footer has been added to zulip.org
-Readme.md updated with zulip.org link 

Screenshot:
footer

### CODE REVIEW

**Comment by timabbott** [comment]
Hi @jajodiaraghav!  The footer looks good (modulo the Dropbox copyright, which isn't needed).  But because of how this site is setup, that will only shown up on the main page, and not on any subpages.  So I'd recommend removing the Dropbox piece, and then copying (ugh) the footer into the other pages.

We'll want to change the system for how this website is managed to not require this sort of copying soon...

**Comment by timabbott** [comment]
Also this should like to the Zulip blog at blog.zulip.org

**Comment by jajodiaraghav** [comment]
@timabbott Done.
capture

**Comment by timabbott** [comment]
Merged, after fixing the trailing whitespace, thanks @jajodiaraghav!

**Pull request closed without merging**
